### ISSUE TITLE
Multiple organizations for a dataset

### ISSUE THREAD

**Issue by sgrellet** [epos-eu/EPOS-DCAT-AP#108]
WP15 webservices are provided by a single organization but datasets served by those services are the aggregation of single datasets provided by multiple organizations (so that there is only one focal point for ICS-C to interact with)

How do we tell this in EPOS-DCAT-AP ?
2 things are missing
- Webservice should point to the dataset served (see issue #36 )
- and we should be able at Dataset level to list all the data providers (using eposap:responsibleParty or eposap:providedBy ?). But so far cardinalities for those elements are max 1...

Not solving this before October will result in **only** the WebService service provider appearing in the GUI (and not the all the providers of the data served by a WebService).

**Comment by nmtoken** [comment]
And/Or we should be able to say that a dataset is comprised of several datasets, each with their own organization

See: https://jira.plgrid.pl/jira/browse/EPOSICS-136?jql=project%20%3D%20EPOSICS (It is not possible to discover how datasets are related).

**Comment by danielebailo** [comment]
This is fixed in revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

**Comment by nmtoken** [comment]
and the answer is...
