### ISSUE TITLE
provide a way to ship URIs and terms

### ISSUE THREAD

**Issue by ulbricht** [epos-eu/EPOS-DCAT-AP#109]
At the moment it is not really obvious if the string inside an XML-element is an URI or a term. Guessing the type is bad. At least the following attributes of a dataset/webservice should provide a way to distinguish between term and URI:
- license
- format
- spatial reference system
- spatial representation type

preferred this way:
&lt;format href="http://my.uri/term" >term</format&gt;

**Comment by nmtoken** [comment]
In ISO 19115 / ISO 19139 metadata, the typical structure to define this is:

<gmd:SomeElement
    codeList=http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#SomeCodeList
    codeListValue="term"/>   

There is also RS_Identifer:

         <gmd:RS_Identifier>
            <gmd:code>Term</gmd:code>
            <gmd:codeSpace>CodeList of terms</gmd:codeSpace>
            <gmd:version>Version of code list</gmd:version>
         </gmd:RS_Identifier>

**Comment by danielebailo** [comment]
this issue has been fixed in revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

**Comment by nmtoken** [comment]
It's great to know it has been fixed, but could you provided an example of how it's been fixed, rather than point to generic documentation.
