### ISSUE TITLE
EPOS-DCAT-AP_WP10.xml issue

### ISSUE THREAD

**Issue by epos-eu** [epos-eu/EPOS-DCAT-AP#110]
@crockercaria 
we refer to this file EPOS-DCAT-AP/examples/WP10/EPOS-DCAT-AP_WP10.xml .
We Found the following issues:

1. Links of webservices provided in the file, don't seem to work, (see below)
http://glass.unice.fr/GlassFramework
http://products.segal.ubi.pt/GlassFramework
Is the server running?

2. Parameters to query the service are not specified. See for instance [GFZ seismological webservice XML description](https://github.com/epos-eu/EPOS-DCAT-AP/blob/master/examples/WP08/EPOS-DCAT-AP_WP08_GFZ.xml) at line #126 
```
   <eposap:parameter>
      <http:paramName>starttime</http:paramName>
      <rdf:label>Start of the timespan</rdf:label>
      <dct:type>
              time
      </dct:type>
    </eposap:parameter>
```

**Comment by crockercaria** [comment]
The corrected links to the portals Web Service root are http://glass.unice.fr:8080/GlassFramework and http://193.136.66.29:8102/GlassFramework

**Comment by manuelasbarra** [comment]
Thank you for the update.
We found the following issues in the files you updated:

** EPOS-DCAT-AP_WP10 - 13-7-2017.xml*

   web services url don't work

  -   http://products.segal.ubi.pt/GlassFramework


<http://products.segal.ubi.pt/GlassFramework>  -
http://glass.unice.fr/GlassFramework


<http://glass.unice.fr/GlassFramework>

* *EPOS-DCAT-AP_WP10.xml*

*1.      **ENTITIES: Person an Organisation *

Person and Organisation identifiers must be unique

for Person:  ORCID, ScopusID, researchgateID ..

for Organisation: PIC, viaf..

for example EPOS.OCA isn’t valid!



*2.      **ENTITIES : Web Service*


- Web service: *EPOS WP10 GNSS Data Porta *
Uri: http://glass.unice.fr:8080/GlassFramework is a link to the gui portal
and is not machine readable

-    Web service: *Station MetaData*

Uri: http://glass.unice.fr:8080/GlassFramework/webresources/stations  we
need parameters for stations  discovery. The actual url return only a list
of all station without the search feature


- Web service: *All Station MetaData from Site Name*

Uri: http://glass.unice.fr:8080/GlassFramework/webresources/stations/site/
doesn’t work

(HTTP Status 404 - Not Found)

Parameter ”Site”: what are the valid values to query the web service?


- Web service : *All Station Data from Marker Name*

Uri:
http://glass.unice.fr:8080/GlassFramework/webresources/stations/files/marker/
Parameter ”Marker”: what are the valid values to query the web service?


- Web service : E*POS WP10 GNSS Products Portal*

Uri: http://193.136.66.29:8102/GlassFramework/swagger.json is a link to a
client (swagger) and not to a web service remove it


- Web service : *Velocities XYZ*

Uri:
http://193.136.66.29:8102/GlassFramework/webresources/products/velocities/xyz/

doesn’t work (HTTP Status 404 - Not Found)

Parameters ” Site – Agency - Format”: what are the valid values to query
the web service?

We have some parameters but how to use them. Can you suggest an example of
search by parameters?



- Web service : *Time Series XYZ*

Uri: *http://193.136.66.29:8102/GlassFramework/webresources/products/timeseries/xyz/
<http://193.136.66.29:8102/GlassFramework/webresources/products/timeseries/xyz/>
*Parameters ”Site – Agency – SamplingPeriod ”: what are the valid values to
query the web service?

We have some parameters but how to use them. Can you suggest an example of
search by parameters?


** **EPOS-DCAT-AP_WP10_ROB_v3.xml* only Person and Organisation are mapped
and not web services are defined. So this file may be removed

I suggest you to refer to the guidelines on github:
https://github.com/epos-eu/EPOS-DCAT-AP/blob/master/docs/GUIDELINES%20FOR%20TCS%20Metadata%20
Mapping.pdf to define your entities please


Best regards

Manuela




-----------------------------------------------------
  Dott.ssa MANUELA SBARRA
  INGV - ISTITUTO NAZIONALE GEOFISICA E VULCANOLOGIA
  U.F.  C.S.I. Centro Servizi Informativi
  Via di Vigna Murata 605
  00143 Rome, Italy
  Tel. 0651860360
-----------------------------------------------------

2017-09-18 0:32 GMT+02:00 crockercaria <notifications@github.com>:

**Comment by crockercaria** [comment]
Dear Manuela

I hope the below helps you - the text is also in the enclosed document.

paul crocker

**Comment by manuelasbarra** [comment]
Dear Paul
see my answer in the inline:



2017-09-18 17:33 GMT+02:00 crockercaria <notifications@github.com>:

> Dear Manuela
>
> I hope the below helps you - the text is also in the enclosed document.
>
> paul crocker
>
>
>  The current url return only a list of all station without the search
feature. So we can't include it.



> All Station WebService from site name
>
> **See documentation in the “GLASS Web Service API” document
> http://glass.unice.fr:8080/GlassFramework/webresources/stations/site/
> Number of Required Parameters 1
> Output : returns the full json information of all EPOS stations that
> contain a given site name
> Example
> http://glass.unice.fr:8080/GlassFramework/webresources/stations/site/CASC


 --->  At the moment we aren't ready to integrate the restfull services
with the @path annotation(
  example "station/site/CASC
<http://glass.unice.fr:8080/GlassFramework/webresources/stations/site/CASC>"
istead of station?site=CASC)
  However the integration could be faciltate if you include in the
parameter tag the allow values in the XML file

     <eposap:parameter>


.....
       <http:paramValue>CASC</http:paramValue>
       <http:paramValue>SOPH</http:paramValue>
       <http:paramValue>   ...   </http:paramValue>
    </eposap:parameter>

  Please consider it a short term solution in order to be integrated before
TRA.
  After that we need further collaboration an discussion.


>
> All Station Data from Marker WebService
>
> **See documentation in the “GLASS Web Service API” document
> http://glass.unice.fr:8080/GlassFramework/webresources/
> stations/files/marker/
>
> Number of Required Parameters 1
> Output : returns all files filtering by MARKER
> Example
> http://glass.unice.fr:8080/GlassFramework/webresources/
> stations/files/marker/CASC
>
>
--- > Currently the example returns an empty json list. We can not
integrate it


> T4 Queries
>
> TIMESERIES Web Service
>
> URL:
> http://193.136.66.29:8102/GlassFramework/webresources/
> products/velocities/xyz/
> Number of Required Parameters 3, Number of Optional Parameters 4
> Output: Timeseries xyz in json format by default (xml format can be used
> adding to the url "format:xml"). In addition to the used parameters
> (which are required), the request may contain outlier, offsets,
> date_start e date_end.
> Example
> http://193.136.66.29:8102/GlassFramework/webresources/
> products/timeseries/xyz/site:ABAS&agency:GEOTOP
> S.R.L.&sampling_period:daily
>
>
 --- > Currently the example returns an empty json list. We can not
integrate it


T5 Queries
>
> VELOCITIES Web Service
>
> URL:
> http://193.136.66.29:8102/GlassFramework/webresources/
> products/velocities/xyz/
> Number of Required Parameters 3
> Output: Velocities xyz in xml or json formats
> Example
> http://193.136.66.29:8102/GlassFramework/webresources/
> products/velocities/xyz/site:ABAS&agency:GEOTOP
> S.R.L.&format:xml
>
>
 --- > At the moment we aren't ready to integrate the restfull services
with the @path annotation
  However the integration could be faciltate if you include in the
parameter tag the allow values in the XML file

 <eposap:parameter>
      <http:paramName>agency</http:paramName>
      <rdf:label>...</rdf:label>
      <dct:type>
              string
      </dct:type>
      <http:paramValue>GEOTOP</http:paramValue>
      <http:paramValue>NGV - PP</http:paramValue>
      <http:paramValue> .. </http:paramValue>
</eposap:parameter>

  Please consider it a short term solution in order to be integrated before
TRA.  After that we need further collaboration an discussion.


>
> Current Agency List
> GEOTOP S.R.L. .. dummy Data ?
> NGV - PP solutions
> UGA - DD solutions
> BFHK - the combined EPOS solutions (using EUREF+INGV+CNRS solutions)
> WUT - EUREF Solutions
> EPOSDEMO - UBI Demos
>
> Sampling_Period
> daily or weekly
>
> -->
>
>
>
>
>
> Best regards
Manuela

**Comment by manuelasbarra** [comment]
Wp10 has been integrated
