### ISSUE TITLE
eposap:publisher - should it be a person or organisation?

### ISSUE THREAD

**Issue by ulbricht** [epos-eu/EPOS-DCAT-AP#116]
There are some inconsistencies concerning the scope of eposap:publisher:

In the example file (https://github.com/epos-eu/EPOS-DCAT-AP/blob/master/examples/EPOS-DCAT-AP_example.xml)  

eposap:WebService/eposap:publisher links to an organisation 

eposap:Publication/eposap:publisher links to a person

However, the definition here https://www.epos-ip.org/terms.html#publisher says eposap:publisher is a person and is an attribute of a publication.

What is correct?

**Comment by nmtoken** [comment]
If a publication requires a publisher who is an individual (person), but a service provides a contact organization (this is an INSPIRE requirement for example), then perhaps a service shouldn't have a eposap:publisher.

For INSPIRE, the contact for a web service is defined by an organization name and a contact email, the contact email does not need to belong to an individual, but can be a group email.

**Comment by manuelasbarra** [comment]
At the moment only Webserver has been implemented
So you can consider eposap:WebService/eposap:publisher links to an organisation
