### ISSUE TITLE
Character lengths of strings

### ISSUE THREAD

**Issue by ulbricht** [epos-eu/EPOS-DCAT-AP#133]
At the moment the XSD definitions of data types differ from the metadata model ( https://docs.google.com/document/d/1awBBniKlyGA_F7H386WIbPMgmreXSyd8NFd_eaHklOc/edit?pref=2&pli=1 ). It is difficult to store such information in the database. A date is sometimes datetime (issued/modified/created) and there is no limit of string lengths (any attribute that contains text). 

We need a decision what information will be stored in the database. Either we revise the XSD to be compliant with the metadata model or we revise our metadata model to be compliant with the XSD and adjust the tables in the database.

**Comment by nmtoken** [comment]
My +1 would be to stick with the INSPIRE / ISO 19139 metadata, rules.

A date can be either Date or DateTime

so either:

`<gmd:dateStamp>
        <gco:Date>2014-06-23</gco:Date>
  </gmd:dateStamp>`

A year on its own is sufficient

or 

`<gmd:dateStamp>
      <gco:DateTime>2017-06-21T00:00:00</gco:DateTime>
 </gmd:dateStamp>`

For INSPIRE metadata, we have two sets of dates.

The first is date of the metadata (i.e. when it was created or updated), it is not typed as such.

The second set relates to the  the data set, or data set series or service.  These dates are typed as revision, creation, and publication.   

INSPIRE metadata is slightly different from what we had in the metadata model, in that you can have one each of revision and creation dates, and multiple publication dates, whereas the metadata model allows only one of each.

When only one date is given INSPIRE metadata guidance is that it should be date of revision.

**Comment by ulbricht** [comment]
The current implementation of the XSD sticks dates to the type DateTime.

**Comment by nmtoken** [comment]
Most resource dates (publication/revision/creation) will probably be in date only format.  Dates of Metadata creation/updated dates are more likely in DateTime (as they are more likely to be automatically created).

Obviously you can convert Date to DateTime  and vice versa, but what is the conversion (Date to DateTime) if the metadata reported the dataset was created in 1998?  Do you convert to 1998-01-01T...  or as 1998-12-31T...  which is the more accurate?

If it is Date or DateTime, then Date is probably the better option.

**Comment by danielebailo** [comment]
This requirement can be satisfied in revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

I'll close the issue in this branch for now, if you verify this requirement is not reflected into EPOS-DCAT-AP with  RDF/turtle serialisation please reopen it there.
