### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by crockercaria** [epos-eu/EPOS-DCAT-AP#154]
Concerning the eposWebService entity
Rest Service Queries may be built using lists of parameters, not all of which are necessary , many may be optional.
How therefore does one specify if a parameter is "required" or "optional"  ?

**Comment by danielebailo** [comment]
At the moment it is not possible to differentiate between optional and required parameters.
It may be included in the next refinement iteration after further discussion.

**Comment by danielebailo** [comment]
This requirement is now supported in the revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

see here for instance
https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP08.ttl#L177
