### ISSUE TITLE
parameter types

### ISSUE THREAD

**Issue by crockercaria** [epos-eu/EPOS-DCAT-AP#158]
Do you need to define the of web service parameter types ? i.e is  Path parameters / Request parameters / etc.
I do not currently see a way of defining the type(s) of the parameters in the epos Webservice entity.

**Comment by crockercaria** [comment]
Hi

I do not mean "data type  - string,int etc"

By type I mean REST Parameter type ..  resource(path), query, matrix.....

yours

paul

**Comment by epos-eu** [comment]
Ok, you are right.
At this stage the inclusion of RESTful web service can't be done properly,
and it needs more discussions to be carried on after TRA.
Let's keep this issue open as a reminder.

thanks

Daniele Bailo, PhD
EPOS Management Office ICT - INGV
Via di Vigna Murata 605, 00143 Rome - Italy
Phone. +39 06-51860728    -    Fax. +39 06-51860507

Curare le scienze e non amare le persone,  è come accendere una torcia e
chiudere gli occhi.
www.epos-eu.org  |  www.danielebailo.it | bit.ly/Bailo-INGV

*Get informed with the EPOS Newsletter
<https://www.epos-ip.org/news-press/newsletters>*


2017-09-19 11:50 GMT+02:00 crockercaria <notifications@github.com>:

**Comment by ximenesuk** [comment]
See also https://github.com/epos-eu/EPOS-DCAT-AP/pull/171 where there are examples of this requirement.

**Comment by crockercaria** [comment]
Parameter types can be specified using for example the openapi v3 spec.
It may be sufficient to follow this standard . see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterObject where the "in"  field defines  four possible parameter locations (path, query, cookie and header)

**Comment by crockercaria** [comment]
Hi Daniel
I would like to now whats happening on this issue as WP10 has web services of the form
/products/velocities/{site}/{analysis_centre}/{coordinates_system}/{format}
i.e that include path parameters. And currently I don't have a way to describe them using 'DCAT'.. Shall we give up for now and wait for "turtle" ? Or shall I write a special WS for ICS that converts one format to another ?
ie
for /products/velocities/{site}/{analysis_centre}/{coordinates_system}/{format} 
write a special WS for ICS that accepts query parameters such as 
/products/velocities?site={site}&ac={analysis_centre}&sys={coordinates_system}&fmt={format}

please inform me as after Lisbon meeting I was left unsure how to proceed.
thanks paul

**Comment by danielebailo** [comment]
Hi Paul
plans haven't changed with respect to Lisbon:
we have to wait for 
a) the new turtle representation and 
b) for the ingestors that are being produced by @wxlfrank (Xiaoliang) and @ulbricht (Damian).

RDF/turtle was finalised 5 days ago, and TCS will be soon contacted. 
as for the ingestors, it's better to discuss via email (rossana.paciello@ingv.it and me), as we are in a rush and comments might not be of interest for all github audience.

cheers

**Comment by danielebailo** [comment]
This requirement can be satisfied in revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

I'll close the issue in this branch for now, if you verify this requirement is not reflected into EPOS-DCAT-AP with  RDF/turtle serialisation please reopen it there.
