### ISSUE TITLE
eposap:webservice ->  Domains and Sub-domains

### ISSUE THREAD

**Issue by epos-eu** [epos-eu/EPOS-DCAT-AP#16]
@rpaciello @manuelasbarra we should be abe to handle a namespace for domain and subodomains.
We already know what Domain terms will be (basially TCS names).
Sub-domains shall be defined by TCS.

In the meanwhile, do you think it would be worth of creating the namespace for domains (list follows)?

1. Seismology
2. Geodesy
3. Satellite data
4. Geomagnetic data
5. Geology
6. Geohazards
7. Georesources
8. Transnational access

**Comment by rpaciello** [comment]
Domains: https://www.epos-ip.org/terms.html#domain
SubDomains: https://www.epos-ip.org/terms.html#subDomain
