### ISSUE TITLE
How to link a WebService identifier to dataset identifiers (or viceversa)?

### ISSUE THREAD

**Issue by MarioLocati** [epos-eu/EPOS-DCAT-AP#17]
Is there a way to tell users which datasets are being served by a webservice using identifiers?
A viable solution could be to add "<dct:relation>" to either webservice or dataset (or both).

Here an example from webservice to dataset
\<dct:relation>
&nbsp;&nbsp;\<rdfs:Resource>
&nbsp;&nbsp;&nbsp;&nbsp;\<eposap:Dataset>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \<dct:identifier>doi:xx.xxxx/xxxxxxxx</dct:identifier>
&nbsp;&nbsp;\</eposap:Dataset>
&nbsp;&nbsp;\</rdfs:Resource>
\</dct:relation>

And here a link from dataset to webservice
\<dct:relation>
&nbsp;&nbsp;\<rdfs:Resource>
&nbsp;&nbsp;&nbsp;&nbsp;\<eposap:WebService>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<dct:identifier>doi:yy.yyyy/yyyyyyyyyyy</dct:identifier>
&nbsp;&nbsp;\</eposap:WebService>
&nbsp;&nbsp;\</rdfs:Resource>
\</dct:relation>

In addition, if we will add attributes for describing the 1) relation type and 2) the role, you may adopt the <dct:relation> for many other purposes, for example linking a webservice to an organization or a person, that will replace <dcat:contactPoint> and <eposap:responsibleParty>.
If we go in this direction, we may adopt the list of possibilities provided by the DataCite schema (https://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf).

relationType (pag.20 of the DataCite schema):
- IsCitedBy
- Cites
- IsSupplementTo
- IsSupplementedBy
- IsContinuedBy
- Continues
- HasMetadata
- IsMetadataFor
- IsNewVersionOf
- IsPreviousVersionOf
- IsPartOf
- HasPart
- IsReferencedBy
- References
- IsDocumentedBy
- Documents
- IsCompiledBy
- Compiles
- IsVariantFormOf
- IsOriginalFormOf
- IsIdenticalTo
- IsReviewedBy
- Reviews
- IsDerivedFrom
- IsSourceOf

contributorType (pag.16 of the DataCite schema)::
- ContactPerson
- DataCollector
- DataCurator
- DataManager
- Distributor
- Editor
- HostingInstitution
- Producer
- ProjectLeader
- ProjectManager
- ProjectMember
- RegistrationAgency
- RegistrationAuthority
- RelatedPerson
- Researcher
- ResearchGroup
- RightsHolder
- Sponsor
- Supervisor
- WorkPackageLeader
- Other

**Comment by nmtoken** [comment]
Coupled resource would be the INSPIRE way to do it

**Comment by nmtoken** [comment]
The is also issue https://jira.plgrid.pl/jira/browse/EPOSICS-139?jql=project%20%3D%20EPOSICS (Not possible to relate a web-service to datasets it operates on in JSON-LD metadata)

**Comment by nmtoken** [comment]
And related: https://jira.plgrid.pl/jira/browse/EPOSICS-136?jql=project%20%3D%20EPOSICS (It is not possible to discover how datasets are related)  which as issue about lineage

**Comment by danielebailo** [comment]
The issue of dataset web service linkage is done through the distribution entity in EPOS-DCAT-AP.
See schema here: https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png
