### ISSUE TITLE
Simple password information

### ISSUE THREAD

**Issue by ximenesuk** [epos-eu/EPOS-DCAT-AP#175]
The [INTERMAGNET webservice](https://github.com/epos-eu/EPOS-DCAT-AP/pull/171/files?diff=unified#diff-d9c49ffe6303070610f39cfb469a2f34R99) requires a password. This isn't a per-user authentication process that might be handled by the AAAI component but a single password presented as an HTML digest. This can't be expressed in the current EPOS-DCAT-AP model. See: gh-171

**Comment by epos-eu** [comment]
As referenced in #215 this cannot be supported.
