### ISSUE TITLE
Discoverable parameter value list

### ISSUE THREAD

**Issue by ximenesuk** [epos-eu/EPOS-DCAT-AP#176]
For simple dictionaries of parameter values the existing model is fine. But it would be desirable to be able to use external or discoverable dictionaries to validate parameter values against. See https://github.com/epos-eu/EPOS-DCAT-AP/pull/171 for an example of this where the allowable values of a parameter are the result request to a web service.

**Comment by epos-eu** [comment]
If I got it right, It looks like a getCapabilities in OGC services.

With the new EPOS-DCAT-AP version you can describe your service in several ways: with a WADL, WSDL, or specifying parameters.

Complex negotiation - like the ones in OGC services - that require several connections before getting to the final data, are not handled within the metadata representation, but at System Level.

I'll close the issue in this branch for now, if you verify this requirement is not reflected into EPOS-DCAT-AP with  RDF/turtle serialisation please reopen it there.
