### ISSUE TITLE
Parameter maxValue for date types

### ISSUE THREAD

**Issue by ximenesuk** [epos-eu/EPOS-DCAT-AP#178]
When a parameter for a webservice is defined as type `date` the `maxValue` might be the current date. Is this implied by omitting the `maxValue` element or leaving it null? Or is the implication any date, even those into the future? 

See https://github.com/epos-eu/EPOS-DCAT-AP/issues/1 which is related to some extent.

**Comment by nmtoken** [comment]
I think it will depend on the service whether a parameter can be omitted.  The metadata should probably state whether a parameter is optional, or conditional, or mandatory.  In some services that allow forecasting the max date might be a date in the future.

**Comment by epos-eu** [comment]
maxValue=today should NOT - in principle -  implied by omitting the maxValue element or leaving it null.

not specifying a value will result in a call that do not include that parameter
