### ISSUE TITLE
Parameter default value

### ISSUE THREAD

**Issue by ximenesuk** [epos-eu/EPOS-DCAT-AP#179]
Would it be possible to extend the model to allow an optional default or initial value to be specified for a parameter to a web service? This value could then be used as a default if not otherwise given, or it could be used to pre-populate GUIs.

**Comment by epos-eu** [comment]
default values are now supported with **schema:defaultValue** in the EPOS-DCAT-AP RDF/turtle here https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP08.ttl#L230

I'll close the issue in this branch for now, if you verify this requirement is not reflected into EPOS-DCAT-AP with  RDF/turtle serialisation please reopen it.
