### ISSUE TITLE
Data type for parameters

### ISSUE THREAD

**Issue by ximenesuk** [epos-eu/EPOS-DCAT-AP#180]
In the current schema the data type of a web service parameter seems to be expressed using the element `dct:type` from the Dublin Core schema. This looks like it was intended to define a resource type rather than a data type. Is there a reason for its use here? Is there any proposal to use a more tightly defined schema that can express specific data types, such as xmlschema-2?

**Comment by epos-eu** [comment]
This requirement can be satisfied in revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

However @ulbricht and @wxlfrank  had comments about datatypes. (see line 173 of https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/examples/example_WP08.ttl in the other branch).

I'll close the issue in this branch for now, and move it to the other branch.
