### ISSUE TITLE
web service metadata: how to do if a first parameter choice is constraining min-max values of following parameters ?

### ISSUE THREAD

**Issue by obsmag** [epos-eu/EPOS-DCAT-AP#181]
How is it possible to define min-max values different for each initial parameter?

_examples from DDSS-006:_

first parameter is the name of the geomagnetic index (**Index**: aa or am or Kp or ...)
that parameter constrains **StartTime** parameter
because each of the geomagnetic index is not getting the same initial date 
aa => 1868-01-01
am => 1959-01-01
Kp => 1932-01-01
etc

**Comment by nmtoken** [comment]
Wouldn't some measure of temporal extent for the whole coverage cater for this?  Do you need to know that am starts from 1959-01-01? what would happen if you entered a date earlier than this?

**Comment by obsmag** [comment]
if you enter a Strat time as 1958-06-01 for am index then the system is just giving access to am data from 1959-01-01.

**Comment by danielebailo** [comment]
Parameters dependencies are usually not supported statically but by content negotiation.
That's why we do not support this currently.
