### ISSUE TITLE
Where, in Metadata, is it possible to indicate that a DDSS is embedded into a Trustworthy Data Repository ? 

### ISSUE THREAD

**Issue by obsmag** [epos-eu/EPOS-DCAT-AP#182]
Some DDSS are part of "Trustworthy Data Repository" = Repository that is getting a formal certification from an International Trans-disciplinary Body (regarding all and various elements from technical requirements to more structural ones)

**Examples of Trustworthy Data Repository (TDR) Certifications/Labels :** 

- ICSU-WDS (https://www.icsu-wds.org/services/certification), 
- CoreTrustSeal (https://www.coretrustseal.org/why-certification/requirements/), 
- Data Seal of Approval (https://www.datasealofapproval.org/en/)

- CLARIN certificate B (http://www.clarin.eu/node/3767)
- DIN 31644 (http://www.nabd.din.de/cmd?level=tpl-art-detailansicht&artid=133059734&committeeid=54738855&bcrumblevel=2&languageid=de)
- DINI Certificate (http://nbn-resolving.de/urn:nbn:de:kobv:11-100182800)
- DRAMBORA (http://www.repositoryaudit.eu/)
- ISO 16363 (http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=56510) 
- ISO 16919 (http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=57950)
- RatSWD (http://ratswd.de/dl/doc/RatSWD_FDZCriteria.pdf)
- TRAC (http://www.dcc.ac.uk/resources/tools-and-applications/trustworthy-repositories)
- Trusted Digital Repository (http://www.trusteddigitalrepository.eu/Site/Trusted%20Digital%20Repository.html)

To get such possibility to indicate that a DDSS is part of TDR is of prior importance for some customers and has to be embedded into the DCAP metadata as an optionnal field with duration indication (as some are performing regular reviews).

**Comment by epos-eu** [comment]
What are the technical advantages of indicating that a repository is Trustworthy?
Do you think it is a priority now?

Perhaps it should be reflected in future versions of EPOS-DCAT-AP extension.

In any case, this requirement can be satisfied in revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes

I'll close the issue in this branch for now, if you verify this requirement is not reflected into EPOS-DCAT-AP with  RDF/turtle serialisation please reopen it there.
