### ISSUE TITLE
Use the two-letters encoding in Language(Person)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#19]
It was decided in the meeting in Rome to use the two-letters encoding (e.g. `en`).
Do **not** use `Eng`!

**Comment by rpaciello** [comment]
added this in documentation excel file

**Comment by nmtoken** [comment]
Why was it decided to use  two letter language codes? 

This clashes with what is allowable in INSPIRE metadata, and used by INSPIRE services in language negotiation.

> Codelist values shall be RFC 4646 5 character codes either, complete (e.g.
en-GB), or abbreviated 2 character codes (e.g. en).

**Comment by javiquinte** [comment]
> abbreviated 2 character codes (e.g. en)

AFAICS this is inline with what it was mentioned in Rome. I don't see any conflict. Or maybe I'm missing something. What it was pointed out is that in many examples **the language code was using a 3-letter coding (not 2, not 5)**. In any case, whatever brings us closer to INSPIRE is always better.

**Comment by nmtoken** [comment]
So to be close to INSPIRE, mandating two letters is wrong.

INSPIRE allows en-GB, en-US, en-UK for example

Also some some European languages don't have a two letter code.

**Comment by danielebailo** [comment]
With the new EPOS-DCAT-AP with  RDF/turtle serialisation you can use the 
`schema:availableLanguage "en" ;`
see here for examples:
https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP08.ttl#L58

Available language codes are reported in here https://tools.ietf.org/html/bcp47#appendix-A

**Comment by nmtoken** [comment]
Good to see that https://tools.ietf.org/html/bcp47#appendix-A does not mandate two letter codes :)
