### ISSUE TITLE
Ability to pass a 'hidden' parameter to a web service

### ISSUE THREAD

**Issue by SimonFlower** [epos-eu/EPOS-DCAT-AP#215]
For auditing purposes we require that some of out web services are passed a 'username' parameter with a contents indicating that that user is EPOS. The user of the web service should not have to supply this parameter, it should be added by the EPOS GUI when calling the web service.

**Comment by epos-eu** [comment]
The implementation of accounting and authorisation mechanisms is something strongly encouraged.
However implementing it with username:password parameters in the URL, within a non secured (http and not https) connection is unfortunately not a state of the art solution, prone to security issues.
The proposed work around (create hidden parameters for login) will not scale in the future and makes integration into ICS  tricky.
The most appropriate way to integrate Accounting and Authentication would be by means of a AAI provider using token and proxies.
In addition to this, requiring login doesn't make datasets openly available. 
(BTW: What is WP13 position with respect to open access? Do you provide open access or restricted? Is it reflected into deliverables?)

For the above reasons, hidden login parameters are not supported at this stage.

**Comment by SimonFlower** [comment]
Hi,

Thanks for responding to the issue we raised. We are interested in AAAI as a solution, since it is the EPOS recommended approach to authentication and logging. The problem we want to solve is to be able to authenticate (and log) who is using the service, not restrict access. I recently attended the AAAI training in Lisbon and it’s not clear to me, following that training, how we would set about implementing an AAAI solution that would allow us to record who is accessing the data via these web services. Is AAAI ready to be deployed now? We need a solution that works now (next few weeks), as this data is part of the WP13 priority data sets and is already overdue for validation in EPOS. If AAAI is ready to be implemented in this way, that would be great. But if not I think we still need a temporary solution involving metadata and web service parameters.

About your question on WP13 data access policy. Nearly all the data we are currently working on is likely to be made available under CC:BY or CC:BY:NC – we already have very open access policies. The issue for us is not attempting to restrict who accesses the data (apart from commercial access to some data sets), rather it’s understanding who is using it (often a critical part of the evidence for why the service needs to continue to be funded for a number of data providers).

Simon.

**Comment by danielebailo** [comment]
Hi,
providing an AAAI solution is not in the plan of EPOS ICS. However in this context ICS-C can act as facilitators creating appropriate linkages with e-Infrastructure providers that can support the adoption of an AAAI service (EUDAT and EGI just to mention a couple).

Accounting of access and usage of your resources is also encouraged, however the workaround you propose is a bit awkward and I'm not sure our BGS colleagues who develop the GUI can support it. 
If the proposed solution is to have 1 account for EPOS ICS (independently from the user who is connected to ICDS), then an alterative solution is simply to log access from the ICS-C IP. This will ease our work at the moment.

Let's also see what  Wayne and Chris think about it.
