### ISSUE TITLE
Missing organisation roles in Facility

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#22]
In the Baseline document there was the chance to relate a Facility to an Organisation with a Role attached to it. This is quite useful for the mapping of networks from Datacite, because there is no such thing as an `owner` (current status of the specification).

**Comment by danielebailo** [comment]
The current EPOS-DCAT-AP with  RDF/turtle serialisation now supports this feature, see UML diagram here
https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png

Now available roles for facilities are:
- contact point, which links to person OR organisation
- owner, which links to organisation
