### ISSUE TITLE
Change cardinality to unbounded in the relation between Facility and Organisation

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#23]
There are actually many Organisations related to a Facility. The cardinality should be unbounded and not 1.

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with  RDF/turtle serialisation cardinality has been set to unbounded.
See UML diagram here https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png

and SHACL https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/epos-dcat-ap_shapes.ttl
for instance at this line
https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/epos-dcat-ap_shapes.ttl#L1528
