### ISSUE TITLE
Document that responsibleParty relates to Organisation (not Person)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#26]
From the discussion in Rome, the responsibleParty is the institution hosting the service (not a Person).
However, it should be noted that there are still discussions about deeper modifications to this attribute, but whatever the conclusions are the relation to a Person is wrong and should be fixed.

**Comment by ltrani** [comment]
I am not aware of the discussion in Rome. In any case in the model responsibleParty is a role associated with an Agent. This can be a Person or an Organisation

**Comment by ulbricht** [comment]
The definitions here https://www.epos-ip.org/terms.html#responsibleparty say responsibleParty is an attribute of a dataset/webservice and points to a person.

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation, the responsibleParty disappeared.
Webservice has now a schema:provider relation that links webservice to a person OR to an organisation.

See UML diagram here https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png
