### ISSUE TITLE
Document codes for representationTechnique in the web service

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#29]
From the discussion in Rome it was clarified that a list of codes from ISO 19115 will be provided and must be included in the documentation.

**Comment by rpaciello** [comment]
W3C recommend the following usage:
"An example of an approach is the way ADMS defines Representation Technique which could be used to describe the type of data in a ZIP file, e.g. dcat:mediaType="https://www.iana.org/assignments/media-types/application/zip"; adms:representationTechnique="https://www.iana.org/assignments/media-types/text/csv".
"
[https://www.w3.org/2017/dxwg/wiki/Use_Case_Working_Space#DCAT_packaged_distributions]

So, we should use the following controlled vocabulary for the representationTechnique:
https://www.iana.org/assignments/media-types/text/

EXAMPLE:
<adms:representationTechnique> 
			xml
</adms:representationTechnique>

**Comment by nmtoken** [comment]
I'm not sure what **XML** would mean in respect to representation technique.  It could be text, or it could be a 3D model, or a style to apply to a map.

**Comment by nmtoken** [comment]
In INSPIRE metadata (as clarified in latest Technical guidance v 2.0.1).  Just four values should be used for Spatial Representation Type (**TG Requirement 2.4**):

- vector

- grid

- tin

- textTable

The values taken from:
http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_SpatialRepresentationTypeCode

We should probably use these unless we have a good reason not to.

**Comment by sgrellet** [comment]
Then we could use this
 http://registry.it.csiro.au/def/isotc211/MD_SpatialRepresentationTypeCode/vector
http://registry.it.csiro.au/def/isotc211/MD_SpatialRepresentationTypeCode/grid
etc...
@nmtoken :  picked the one at CSIRO not having another one at hand so far. Are you aware of a 'organization neutral' URI I could use (ex : directly bound to ISO TC211 ?)

**Comment by nmtoken** [comment]
Not aware of any alternative URIs

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation `representationTechnique` was removed.

See SHACL https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/epos-dcat-ap_shapes.ttl
