### ISSUE TITLE
Document how to inform the Spatial reference system in web service

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#30]
Document an example like `EPSG:4326`. Include in the documentation.

**Comment by rpaciello** [comment]
Done.

**Comment by nmtoken** [comment]
Document should have HOW this code will be used.  If the intention is that it will be appended to some dereferencer then _EPSG:4326_ will most likely be be incorrect.

Note that the **Definition identifier URNs in OGC namespace, 07-092r1, 2007** document tells us that:

To identify the definition of a single object, the URN shall have the form:

**urn:ogc:def:objectType:authority:version:code**

and

the URN value for an anyURI that references one object in the European Petroleum Survey Group (EPSG) database shall have the form:

**urn:ogc:def:objectType:EPSG:version:code**

Note that:

The urn, ogc, def, and six: parts of this URN are fixed.

'This' references the URN for the definition of a single object, that means that urns without the optional version should have a double colon in them like:

**urn:ogc:def:crs:EPSG::4326**

See also:
https://jira.plgrid.pl/jira/browse/EPOSICS-142?jql=project%20%3D%20EPOSICS

**Comment by sgrellet** [comment]
You may also want to authorize the URL way (since OGC finally agreed to move from URN to URL).
this will mean for 4326 -> http://www.opengis.net/def/crs/EPSG/0/4326

**Comment by javiquinte** [comment]
At the beginning of the meeting there was one example with `EPSG:4326` and another with the full URL. At some moment someone (I cannot remember who) decided to use the short version. What ever it is used it would be nice to see it in an example, good documented and at least one link to check what other options/values are available.

**Comment by nmtoken** [comment]
For those who can't access Jira, in the original documentation the comment was 

> Spatial Reference System the CRS should be specified with the relevant URI from the OGC EPSG register.
The base URI is: http://spatialreference.org/ref/

and the code was given as:

<dct:conformsTo>EPSG:4326</dct:conformsTo> 

This advice was incorrect because there is no resource   http://spatialreference.org/ref/EPSG:4326

The question to be answered / documented is how will the projection code be used?  
That will answer the question of what form the codes should take.

**Comment by rpaciello** [comment]
As written in the example file the base URL is  http://www.opengis.net/def/crs/

**Comment by nmtoken** [comment]
So that is incorrect advice, because there is no resource:  http://www.opengis.net/def/crs/EPSG:4326

If _http://www.opengis.net/def/crs/_ is the base then the code should be:

**EPSG/0/4326** or **EPSG/0/27700**

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
Spatial reference system is not a property of webservice anymore.

See also SHACL file https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/epos-dcat-ap_shapes.ttl

**Comment by nmtoken** [comment]
Does this mean there is no way for a user to know what projections a service supports?
