### ISSUE TITLE
Document what actually the temporal extent applies to (web service)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#31]
Temporal extent: related to the data covered by the WS. Please, document it clearly.

**Comment by rpaciello** [comment]
Done.

**Comment by nmtoken** [comment]
Where has it been done?  

Is it https://github.com/epos-eu/EPOS-DCAT-AP/blob/master/docs/EPOS_DCAT-AP_Vocabulary_and_Specification.xlsx

> 

dct:temporal | eposap:WebService | dct:PeriodOfTime | String | [0..1] | This property
  refers to a temporal period that the data covers by WS
-- | -- | -- | -- | -- | --

This isn't particularly clear: (_a temporal period_)

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
temporal extent is not a property of webservice anymore.

See also SHACL file https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/epos-dcat-ap_shapes.ttl
