### ISSUE TITLE
Include only default distribution format in web service

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#32]
From the discussion in Rome, it was agreed that for the first release only the default distribution format will be informed for a web service. For instance, only the proper MIME type for StationXML and **not** the text output.

**Comment by rpaciello** [comment]
changed cardinality of distribution format in web service to 1..1

**Comment by nmtoken** [comment]
What if there is no default

**Comment by nmtoken** [comment]
So I have a web service (a WFS or a WMS) and it has multiple different operations and each has multiple formats, none of which are default, which should be used, or should we specify none?

In the GUI interactions.docx document (https://github.com/epos-eu/WebApi/blob/master/DOCS/GUI%20interactions.docx) circulated on the 11/7/2017 we have an operation **(/process?url=serviceURL&op=theop&format=theformat**) that allows a list of multiple formats to be shown to the user, how does the UI get this list?

**Comment by sgrellet** [comment]
I am currently mapping WP15 BoreholeDataIndex WMS. 
As pointed out above, a WMS has multiple operations each of them can have multiple output formats.
I can try and advise a 'default' format (ex : https://www.iana.org/assignments/media-types/image/png) for the GetMap Operation but EPOS-DCAT-AP prevents me to put more formats for the operation.
=>Does that mean that I should map only the GetMap operation under <epos:WebService> and forget the rest ? I am proposing the GetMap because there is a plan to interact with WMS in the GUI

Same question will work for the WFS => should I only map the GetFeature because in the GUI we want to trigger searches ?

On the other hand I guess the non GUI part of the ICS-C needs the GetCapabilities as well no ?

**Comment by javiquinte** [comment]
The issue was more related to WP8 than anything else. Many of the standard WS have a parameter `format` allowing you to choose the output format. Now I cannot remember if this *uncertainty* (as it is decided by the user in runtime) brought some problem to the approach taken by the ICS. Or probably it was that the distribution format cardinality was "0|1". So the *default* does not mean that it actually should exist a default value, but that we saw in our services that usually existed one format which was enough.

**Comment by nmtoken** [comment]
It seems odd to change cardinality on the basis that one service only has a single format, why would you need to change the cardinality on that basis? 

It is correct that OGC web services (OWS)  have parameters that deal with format (I know of **format**,  **info_format**, and **EXCEPTIONS**) , but we still have a different set of formats per operation which is an issue.

Let's say I provide a list of available operations for a WMS (specified through the **request** parameter):

`        <eposap:parameter>
            <http:paramName>request</http:paramName>
            <rdf:label>Type of operation requested, (one|MANDATORY)</rdf:label>
            <dct:type>string</dct:type>
            <http:paramValue>GetCapabilities,GetMap,GetFeatureInfo,DescribeLayer,GetStyles</http:paramValue>
        </eposap:parameter>`

and a list of possible values for a format parameter like:

`        <eposap:parameter>
            <http:paramName>format</http:paramName>
            <rdf:label>format of data requested, (one|CONDITIONAL)</rdf:label>
            <dct:type>string</dct:type>
            <http:paramValue>text/xml, image/png,image/jpeg,image/png;mode=8bit,application/x-pdf,image/svg+xml,image/tiff,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kmz</http:paramValue>
        </eposap:parameter>`

1.  How will the user know which formats go with which operation?

2. Are you saying that the format parameter values will be extracted, as well as dct:format > dct:MediaTypeOrExtent> from the metadata , and this will be used to populate the list of offered formats as per the GUI interactions.docx documentaion, or are you just proposing it as a workaround.


Increasingly I'm feeling that it will not be possible to map the complexity of an OGC web service into CERIF (oh the irony), and it would be better to just document the capabilities document and leave all the intelligence on how to use the service to the GUI/API/Workflow engine.

**Comment by sgrellet** [comment]
> "it would be better to just document the capabilities document and leave all the intelligence on how to use the service to the GUI/API/Workflow engine." 
+1 on this. the system will gain in genericity

Other consequences of such restriction are described in my pull request from this morning #84 

> I have the feeling we are trying to find the pattern to describe OWS in DCAT-AP (sure nobody ever tried that before ?)
> If we want to go that route, some ideas below
- An epos:WebService may have several operations, each of the having 0..* parameters and 1..* formats
but looking at the initial UML (in DCAT-AP), an issue may come with dct:format. 
DCAT:Webservice is a subtype of DCAT:Distribution that mandates 1 dct:format. And, in the proposal above we ask for restructuring WebService and authorizing more than one format...

- Other, related issue, to what extent is DCAT:WebService officially in DCAT (it does not appear in W3C Recommendation 16 January 2014 http://www.w3.org/TR/2014/REC-vocab-dcat-20140116/) but only in a W3C Working Draft 05 April 2012 (https://www.w3.org/TR/2012/WD-vocab-dcat-20120405/#vocabulary-overview) ? This question to try and assess the margin of maneuver if WebService (DCAT: or EPOS:) needs adjustment. 
An option would be to discuss those topics with P.Archer

**Comment by nmtoken** [comment]
Also realised that a WMS GetFeatureInfo requires TWO media formats to be specified in a request

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
dct:format has the original DCAT-AP cardinality, i.e. 0|1

**Comment by nmtoken** [comment]
So does that  mean the GetFeatureInfo request can't be documented because it requires two formats to be specified per single request?
