### ISSUE TITLE
Recognizable term to select a convertor in the 'distribution format' of Web service

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#34]
For instance, `StationXML`and **not** `text/xml`. This should be clearly documented and probably validated when metadata is provided to EPOS.

**Comment by rpaciello** [comment]
W3C recommend the following usage: 
"An example of an approach is the way ADMS defines Representation Technique which could be used to describe the type of data in a ZIP file, e.g. dcat:mediaType="https://www.iana.org/assignments/media-types/application/zip"; adms:representationTechnique="https://www.iana.org/assignments/media-types/text/csv".
"
[https://www.w3.org/2017/dxwg/wiki/Use_Case_Working_Space#DCAT_packaged_distributions]

So, we should use the following controlled vocabulary for the distribution format: 
https://www.iana.org/assignments/media-types/application/

EXAMPLE:
<dct:format>
		<dct:MediaTypeOrExtent>zip</dct:MediaTypeOrExtent>
</dct:format>

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
'distribution format' of Web service can be one of the elements of this codelist (as defined by DCAT-AP):

see example
https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP08.ttl#L394
