### ISSUE TITLE
Resource type changed to list of operations/actions in web service

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#35]
From the discussion in Rome @danielebailo clarified that in 'Resource Type' a comma-separated list of actions inside a tag `eposap:operation` should be specified. These can be selected from a controlled vocabulary list of terms/actions prepared by ICS.

**Comment by ltrani** [comment]
I strongly recommend to change this (but after the service validation). It would be better to have multiple operation elements with a single value instead of one element with multiple comma-separated values. This would facilitate parsers, validators and use of controlled vocabularies.

**Comment by nmtoken** [comment]
A controlled vocabulary that already exists is:

http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory

A WMS would be identified as: http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService

A WFS would be identified as: http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoFeatureAccessService

A WCS would be identified as: http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoCoverageAccessService

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
the metadata model and the way to handle operations at EPOS ICS web-api level has changed.

Now supported operation can be defined in webservices through hydra vocabulary.
See UML diagram here https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png

See also this example: 
https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP15.ttl#L99
