### ISSUE TITLE
'Coupled resource' should be deleted from web service

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#36]
During the discussion in Rome the decision to remove the 'Coupled resource' from the web service was taken in agreement with @danielebailo . Mainly because this is meant to be used for data(sets).

**Comment by rpaciello** [comment]
done.

**Comment by nmtoken** [comment]
This thinking is wrong, coupled resourced is used by both datasets and web services.   For a quick ref see: http://inspire.ec.europa.eu/glossary/MetadataElement-CoupledResource

**Comment by sgrellet** [comment]
+1 the way it is used in INSPIRE. And, looking both at the .eap and EPOS_DCAT-AP.xsd, I don't any alternative route. If you remove this how can we point from the webservice back to the dataset ?

**Comment by javiquinte** [comment]
As already expressed in the issue, during the meeting it was decided to remove it as it was not clear that in the web service entity could be useful. I have no strong opinion about that.
@sgrellet Could you provide an example of the link to the dataset? AFAICS the cardinality is "0|1".

**Comment by nmtoken** [comment]
Also related: https://github.com/epos-eu/EPOS-DCAT-AP/issues/17

**Comment by nmtoken** [comment]
Also related:

https://docs.cyfronet.pl/display/EPOSICS/TCS+HARVESTING?preview=%2F25526881%2F25526982%2Fc4d-cerif-mapping-v0-1.xlsx

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
Coupled resource  is not a property of webservice anymore.

**Comment by nmtoken** [comment]
Wow, even though it was marked as required in the baseline.

**Comment by ltrani** [comment]
There is a way to relate a Dataset with a Webservice i.e. via Distribution. A Webservice is a Resource in itself irrespective of datasets and therefore it can be associated with one ore more SKOS concepts. When required hydra:Operation or hydra:APIDocumentation can be used to describe the types returned by a service.

**Comment by nmtoken** [comment]
As long as it is possible in the metadata for a web service to document which datasets (one or more)  it operates on,  (and the corollary) for a dataset to identify which web services (one or more) provide access/some representation of, or to, it, then that's fine.
