### ISSUE TITLE
'Data service type' should consist of domain and subdomain (web service)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#37]
From the discussion in Rome it was specified that there should be an eposap:domain and an eposap:subDomain attribute. For the WP8 the domain is fixed 'Seismology'. TCSs will provide the list of subdomains. Please, add to the documentation the list of terms as soon as they are available.

**Comment by rpaciello** [comment]
added domain and subdomain element
