### ISSUE TITLE
Expected values of License (Web service) need clarification

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#40]
In Rome it was specified that this is a License of the service, **not from the data**. ICS should provide examples of possible Licenses. Please, check and describe thoroughly in the documentation. One possibility would be to delete this attribute, because this is neither data nor software.
There were comments that the License for the usage of a service is actually related to the License of the **software**!
Conclusion: No one seems to have a clear idea how this should be implemented or if this is really needed considering that 'Access rights' are already in the entity.

**Comment by rpaciello** [comment]
For now we change cardinality of dct:license to 0...unbounded

**Comment by nmtoken** [comment]
For a **service** as opposed **web service** License could apply to software, so that might be a source of confusion.

**Comment by nmtoken** [comment]
For a web service I have mapped **dct:licence** to an OGC service **AccessConstraints** element, and it might have content such as:

> <dct:license>This service is for non-commercial use only. Neither the PSI datasets nor any results derived from this Terrafirma data may be used for commercial purposes. For full terms and conditions for use of the data please see: http://ogc.bgs.ac.uk/BGS_ESA_EN_Terrafirma/docs/141219_TF 1GE_Terms Conditions_v3.pdf</dct:license>

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
Expected values of License is  a dct:license document.

DCAT is vague about the type of resource, but in this discussion
https://joinup.ec.europa.eu/release/dcat-ap-how-refer-licence-documents-and-licence-uris
the recommendation is "_Licences should always be identified with URIs, which should resolve to the description of the licence."_
