### ISSUE TITLE
'Public access limitations' needs a controlled vocabulary list from ICS

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#41]
According to what it was decided in Rome, ICS must provide a list of controlled vocabulary and document it clearly so that TCSs can fill the metadata.

**Comment by rpaciello** [comment]
We are now in contact with all TCSs communities (some of them already provided feedback), produced the metadata editor (http://epos.cineca.it/apache/mde/public/index.php) and will soon issue a document with explanation in the official technical documentation repository (https://github.com/epos-eu/documentation).
