### ISSUE TITLE
Reflect in the documentation the added version at the top level of Webservice

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#43]
We added a version at the top level of web service but the documentation must be updated consistently.

**Comment by rpaciello** [comment]
Done. We added dct:hasVersion in WS

**Comment by nmtoken** [comment]
To what does the  **dct:hasVersion** apply to for an OGC web service implementation, (each implementation supports multiple versions of the implementation standard)?  Is it equivalent to an updatesquence number?

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation 
we have a new class hydra:APIdocumentation which represents info about web services documentation.

See UML diagram here https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png
