### ISSUE TITLE
IriTemplateMappingShape duplicate entry for range

### ISSUE THREAD

**Issue by nbrinckm** [epos-eu/EPOS-DCAT-AP#431]
Hi there,
we at GFZ wonder why there is a duplicate entry for the range property in the IriTemplateMappingShape.

```
sh:property [
      sh:path rdfs:range ;
      sh:datatype xsd:string ;
      sh:minCount 1 ;
      sh:maxCount 1 ;   
  ] ;
  sh:property [
      sh:path rdfs:range ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;   
  ] ;
```

I thinkt the second entry with just the maxCount is not necessary.
Does I miss something?

**Comment by rpaciello** [comment]
Yes, you are right.
I have just accepted your pull request.
Thank you.
