### ISSUE TITLE
Add an attribute to web service to save a URL pointing to the specification

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#44]
The document is meant to be human readable (e.g. PDF, doc, and so on). This will help a user who, for instance, does not understand something from the hints/label of the parameters.

**Comment by rpaciello** [comment]
Added schema:documentation element in WS

**Comment by nmtoken** [comment]
Let's say for an OGC WMS I have the following parameter block to define the versions of the WMS interface standard supported by the service.

```
        <eposap:parameter>
            <http:paramName>version</http:paramName>
            <rdf:label>Version of service requested, (one|CONDITIONAL)</rdf:label>
            <dct:type>string</dct:type>
            <http:paramValue>1.3.0,1.1.1,1.1.0,1.0.7,1.0.0</http:paramValue>
        </eposap:parameter>
```

What would the expectation be for the schema:documentation?

Could it be just:

`<schema:documentation>http://www.opengeospatial.org/standards/wms</schema:documentation>`

**Comment by rpaciello** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation
we have a new class hydra:APIDocumentation which represents info about web services documentation.

See UML diagram here https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png
