### ISSUE TITLE
Document the usage of schema:minValue and others (web service/parameter)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#48]
Examples will be important to show how to use this in conjunction with parameterValue.

**Comment by rpaciello** [comment]
There are some example of EPOS-DCAT-AP extension in RDF/turtle serialisation in this folder:
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes/examples
