### ISSUE TITLE
ICS to provide list of parameterValue types (web service)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#49]
ICS should provide a controlled vocabulary list of value types. For instance, int, float, string, and so on. To avoid the cases of confusion with int, INT, integer, longint, etc.

**Comment by nmtoken** [comment]
Perhaps we should use the XML Schema datatypes https://www.w3.org/TR/xmlschema11-2/

**Comment by sgrellet** [comment]
+1 this is something I wondered when describing parameter for 'BoreholeDataIndex_WFS-DCAT-AP.xml'

**Comment by danielebailo** [comment]
This is fixed revised EPOS-DCAT-AP with  RDF/turtle serialisation, by using xsd types. See here: 
https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP08.ttl#L181
