### ISSUE TITLE
The identifier does not accept special characters

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#51]
From the validation of XMLs we receive an error for IDs like `orcid:0000-0000-0000` because the character ':' is not allowed.

**Comment by rpaciello** [comment]
Fixed.

**Comment by nmtoken** [comment]
The issue was that though the documentation said use a URI, the type on the identifier was xsd:ID, which doesn't allow colons.  The applied fix has been to change the type to xsd:anyURI

**Comment by javiquinte** [comment]
Great! Should the issue be mark as solved yet? Or is it something pending?

**Comment by nmtoken** [comment]
It depends on whether the applied fix now will work for any  unique identifier that a metadata record might wish to use.

**Comment by rpaciello** [comment]
This issue has been fixed using xsd:anyURI.
