### ISSUE TITLE
Add Publication to Dataset, Project, WebService, Service, Equipment, Facility

### ISSUE THREAD

**Issue by MarioLocati** [epos-eu/EPOS-DCAT-AP#53]
During the discussion emerged the need to provide human readable documentation (articles, reports, text on webpages) describing elements.
We discussed in detail the usefulness of providing the documentation describing the changes between two version of a webservice, and then we discussed its use for other elements too.
The final proposal is to add the "eposap:Publication" with minOccurs="0" and maxOccurs="unbounded" to all relevant elements ("Dataset", "WebService", "Equipment", "Facility", "Project", "Organisation", "Person", "Service").
This proposal comes from the DCAT meeting with WP8 in Rome on the 21st of June 2017.

**Comment by danielebailo** [comment]
This issue everything changed, documentation and changes about the mentioned elements can be specified with the "annotation" class.
