### ISSUE TITLE
Add dct:type to eposap:Publication

### ISSUE THREAD

**Issue by MarioLocati** [epos-eu/EPOS-DCAT-AP#54]
While discussing the usefulness of providing documentation for DCAT elements such as the webservice, a solution for scifying the type of provided documentation emerged.
The final proposal is to add "dct:type" to the complex element "Publication" with minOccurs="0" and maxOccurs="1", and adopting a controlled list with the same types adopted in the widely used BibTeX format (https://en.wikipedia.org/wiki/BibTeX#Entry_types).
This proposal comes from the DCAT meeting with WP8 in Rome on the 21st of June 2017.

**Comment by danielebailo** [comment]
This is fixed revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes
