### ISSUE TITLE
Add dct:spatial to eposap:Publication

### ISSUE THREAD

**Issue by MarioLocati** [epos-eu/EPOS-DCAT-AP#55]
During the discussion on the way AHEAD (European Archive of Historical Earthquake Data) use publications (is the main source of data for describing earthquakes), emerged the need to provide spatial information associated to a publication.
As AHEAD will expose a bibliographical webservice, it will enable EPOS ICS users to retrieve all publications containing seismological information about a user selected geographical area.
The proposal is to add the "dct:spatial" to the complex element "Publication" with minOccurs="0" and maxOccurs="unbounded", as a publication might covers multiple areas.
This proposal comes from the DCAT meeting with WP8 in Rome on the 21st of June 2017.

**Comment by danielebailo** [comment]
This is fixed revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes
