### ISSUE TITLE
add element "dct:license" into complexType "Dataset" and "Publication"

### ISSUE THREAD

**Issue by MarioLocati** [epos-eu/EPOS-DCAT-AP#65]
It should be possible to associate a license into both a "Dataset" and into a "Publication", so, please, add the element "dct:license" into complexType "Dataset" and "Publication".

**Comment by danielebailo** [comment]
This is fixed revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes
