### ISSUE TITLE
It should be possible to report multiple supported coordinate reference systems for a Web Service

### ISSUE THREAD

**Issue by nmtoken** [epos-eu/EPOS-DCAT-AP#82]
Originally  **dct:conformsTo** had unbounded  cardinality for a web service allowing multiple coordinate reference systems to be reported. 

For some reason this has been changed to allow a maximum of one.

**Comment by sgrellet** [comment]
I am currently mapping WP15 BoreholeDataIndex WMS.
Only one is not common best practice. Should our service only support the SRS planned to be implemented in the GUI ? It yes, what would that be ?

**Comment by danielebailo** [comment]
This is fixed revised EPOS-DCAT-AP with  RDF/turtle serialisation here: 
https://github.com/epos-eu/EPOS-DCAT-AP/tree/EPOS-DCAT-AP-shapes
