### ISSUE TITLE
Format of identifiers

### ISSUE THREAD

**Issue by jan-michalek** [epos-eu/EPOS-DCAT-AP#91]
Some questions about identifiers after checking several XML files from various WPs. 

**Person entity:**  `<dct:identifier> orcid0000-0002-9733-284X </dct:identifier> <!-- Person-->`
1. Will other IDs than ORCID be accepted in Person entity? Should we then introduce type of the identifier?
2. What format to use? (comma separated: orcid,00-01; underscore: orcid_0001, no separator?; dashes/no_dashes?) 

**Organisation entity:**  `<eposap:affiliation>PIC999472675</eposap:affiliation> <!-- Organisation -->` 
1. Some organisations do not have PIC (e.g. BGS). Should they register in European Commission portal (https://ec.europa.eu/research/participants/portal/desktop/en/)? Who should register the organisation? 
2. Alternatives to PIC?
3. What format (similarly to Person ID)?

**Comment by sgrellet** [comment]
could those IDs be provided by the granularity database ?...

**Comment by rpaciello** [comment]
For **ORCID** is better to use this format:
http://orcid.org/0000-0002-6975-1991

For **PIC** is better to use this format:
PIC:999472675
